### ISSUE TITLE
Create a heroku button for this app?

### ISSUE THREAD

**Issue by djcp** [heroku/sudo-sandwich#10]
It might be nice to create a [heroku button](https://devcenter.heroku.com/articles/heroku-button) for this app, similar to what we have  for the old [addon-template](https://github.com/heroku/addon-template) example.

**Comment by jessieay** [comment]
Added one! https://github.com/heroku/sudo-sandwich/pull/11

But I think we should add more docs on how to get it going as button app because it will not work unless someone has created an add-on with Heroku as well.

**Comment by jessieay** [comment]
feedback from ransom: move below manifest stuff

**Comment by djcp** [comment]
Nice!
