### ISSUE TITLE
Instructions for setting up a fork

### ISSUE THREAD

**Issue by mathias** [heroku/sudo-sandwich#18]
Hi @jessieay !

Just some notes on setting up a fork and a request that we cover it in the README. (There's a lot of coverage in the README now of how it works, and that's great, but nothing AFAIK about setting up another sudo-sandwich instance.)

Things I ran into (easily fixed):
- Set SLUG and PASSWORD env vars to what is in the manifest
- Set the secret for attr_encrypted in `ENV['ENCRYPTION_KEY']` -- need guidance as to size / how to generate it "correctly", though -- I used `SecureRandom.hex(32)`.
- SSO didn't work -- I had to set `ENV['SSO_SALT']` to what my generated manifest had for `"sso_salt"`.

Other notes (probably should have opened another Issue, sorry):
- We're logging all parameters and we probably want to filter them. Although, for dev usage, this is helpful to know what was sent.
- Catch some errors on provisioning failure and return a helpful JSON error rather than nothing. the Failed Attempts table didn't help me with any of the above, and I had to go into the Heroku app logs.

**Comment by mathias** [comment]
Above should also be taken as "I will write this README section if it sounds good to you"

**Comment by jessieay** [comment]
Great points above! I think adding to the README or CONTRIBUTING sounds perfect.

I tried to add some pointers on these ENV vars in the sample env file: https://github.com/heroku/sudo-sandwich/blob/master/.example.env

But I agree that more explicit would be much better 👍

**Comment by mathias** [comment]
Another necessary step: Scale up the worker process (defined in the `Procfile`) so that it has at least 1 dyno.

**Comment by mathias** [comment]
If #19 merges to master, we can include instructions for adding a Rollbar add-on (should just be a call to `heroku addons:create rollbar --app $APPNAME`.
